{"description": "An issue discovered in Python Charmers Future 0.18.2 and earlier allows remote attackers to cause a denial of service via crafted Set-Cookie header from malicious web server. This issue has been patched in version 0.18.3.", "methods": ["Sent malicious HTTP requests to trigger a denial of service.", "Exploited a vulnerability in a web application."]}