{"description": "It was discovered that pyOpenSSL incorrectly handled memory when performing operations on a PKCS #12 store. A remote attacker could possibly use this issue to cause pyOpenSSL to consume resources, resulting in a denial of service.\n\nThis attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection that would cause the calling application to reload certificates from a PKCS #12 store. This vulnerability appears to have been fixed in 17.5.0.", "methods": ["Consumes resources to cause a denial of service.", "Exploits incorrect memory management in pyOpenSSL.", "Initiates a TLS connection to reload certificates from a PKCS #12 store."]}