{"description": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field.", "methods": ["Used a divide-by-zero error in the function mdb_env_open2 to cause a crash.", "Exploited a bug in the function mdb_env_read_header to obtain a zero value for a certain size field."]}